version: '3.9'

services:
  db:
    image: "postgres"
    hostname: "assistant-db"
    container_name: "assistant-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=assistant
      - POSTGRES_USER=assistant
      - POSTGRES_DB=assistant

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - ./token.json:/token.json
    environment:
      - DATABASE_URL=postgresql://assistant:assistant@db:5432/assistant
      - APP_SETTINGS=config.DevelopmentConfig
      - EMAIL_USER=
      - EMAIL_PASSWORD=
      - MAIL_DEFAULT_SENDER=
      - SPEECH_RECOGNITION_MODEL_SIZE=base
      - GOOGLE_CREDENTIALS_FILE=/Users/slbmax/Downloads/assistant.json
      - GOOGLE_TOKEN_FILE=/token.json
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    depends_on:
      - db
    command: ["sh", "-c", "flask db upgrade && python3 manage.py run"]

volumes:
  postgres_data:
