version: '3.9'

services:
  db:
    image: "postgres"
    hostname: "assistant-db"
    container_name: "assistant-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=assistant
      - POSTGRES_USER=assistant
      - POSTGRES_DB=assistant

volumes:
  postgres_data:
